In [2]:
import numpy as np

## 1、创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1

In [16]:
arr1=np.array(np.zeros(10,dtype=int))
arr1[4]=1
arr1

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

## 2、创建一个元素为从10到49的ndarray对象

In [18]:
arr2=np.array(np.arange(10,50))
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 3、将第2题的所有元素位置反转

In [19]:
arr3=arr2[::-1]
arr3

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## 4、使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素

In [28]:
arr4=np.random.random([10,10])
arr4

array([[0.10393178, 0.38163338, 0.20520643, 0.75047799, 0.88224646,
        0.32762872, 0.39777654, 0.84147067, 0.52851842, 0.45209474],
       [0.11371066, 0.49129899, 0.79316948, 0.68753407, 0.84651711,
        0.14268107, 0.16689346, 0.49257584, 0.08444923, 0.42848865],
       [0.31660449, 0.04840338, 0.11048133, 0.46153356, 0.09072304,
        0.53401052, 0.98162028, 0.08767934, 0.17729336, 0.37364145],
       [0.39077208, 0.82110946, 0.91845825, 0.64629231, 0.76624853,
        0.01581813, 0.20685305, 0.99887028, 0.62315741, 0.41612766],
       [0.65287938, 0.61180935, 0.49919591, 0.42739006, 0.03879157,
        0.63038913, 0.94782683, 0.0993594 , 0.40855686, 0.23818419],
       [0.2324665 , 0.82889388, 0.43418582, 0.02197193, 0.85725677,
        0.25430094, 0.05654899, 0.59695418, 0.05903163, 0.91103638],
       [0.83213764, 0.7562101 , 0.25856387, 0.83426679, 0.91995826,
        0.44838598, 0.03724122, 0.58202562, 0.46933492, 0.66942347],
       [0.45774158, 0.97782029, 0.5949467

In [29]:
np.max(arr4)

0.9988702773269375

In [30]:
np.min(arr4)

0.0020185997960442403

## 5、创建一个10*10的ndarray对象，且矩阵边界全为1，里面全为0

In [120]:
arr5=np.zeros([10,10],dtype=int)
arr5[0]=1
arr5[-1:]=1
arr5[1:-1,0]=1
arr5[1:-1,-1:]=1
arr5

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

## 6、创建一个每一行都是从0到4的5*5矩阵

In [134]:
arr6=np.zeros([5,5],dtype=int)
arr6[::]=np.arange(5)
arr6

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

## 7、创建一个范围在(0,1)之间的长度为12的等差数列

In [159]:
arr7=np.arange(12)
arr7[::]=1
arr7[::2]=0
arr7

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

## 8、创建一个长度为10的随机数组并排序

In [165]:
arr8=np.random.random(10)
np.sort(arr8)

array([0.07810785, 0.26901394, 0.31985558, 0.33278555, 0.41171905,
       0.57050774, 0.78547536, 0.79319765, 0.88871583, 0.91627602])

## 9、创建一个长度为10的随机数组并将最大值替换为0

In [199]:
arr9=np.random.randint(100,size=[10])
max_arr=np.max(arr9)
result_index=arr9==max_arr
result_index
arr9[result_index]=0
arr9

array([16, 72, 25, 42, 93,  7, 16, 11,  0, 22])

## 10、如何根据第3列来对一个5*5矩阵排序？

## 11、给定一个4维矩阵，如何得到最后两维的和？

## 12、给定数组[1, 2, 3, 4, 5]，如何得到在这个数组的每个元素之间插入3个0后的新数组？

## 13、给定一个二维矩阵，如何交换其中两行的元素？